### ISSUE TITLE
Menu - Novo documento - Tela não muda

### ISSUE THREAD

**Issue by kaleopiasse** [leandroscramos/projeto#2]
**Fluxo:**

Gestão de documentos -> **Novo documento**

Nessa tela ao clicar em Cadastros -> **Tipos de Processos** || **Macroprocessos** || **Processos**

A tela não muda, permanece em **Novo documento**

**Comment by leandroscramos** [comment]
Realmente, a parte dos processos não está implementada.

É a próxima tarefa pois preciso dela para partir para o documento.

**Comment by leandroscramos** [comment]
Tela de Novo documento implementada
