### ISSUE TITLE
[Cadastro] -> [Tipo de Documento] - Colocar dica do formato correspondente

### ISSUE THREAD

**Issue by kaleopiasse** [leandroscramos/projeto#23]
Ao tentar cadastrar um novo tipo de documento, colocando apenas 2 caracteres no campo sigla, o usuario recebe um erro ao salvar, mas a interface não da nenhuma dica de qual o formato correto

![image](https://user-images.githubusercontent.com/13857495/90541339-db400900-e158-11ea-8f8a-b88992dffa80.png)

**Comment by leandroscramos** [comment]
![image](https://user-images.githubusercontent.com/12849624/90991028-64ea3f00-e57c-11ea-9ca5-f38eefff0ba6.png)

**Comment by leandroscramos** [comment]
placeholder incluído para orientar sobre a Sigla.
